---
- name: Configure MongoDB 7.0 Repository
  hosts: all
  become: true
  tasks:
    - name: Import MongoDB GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://pgp.mongodb.com/server-7.0.asc

    - name: Add MongoDB 7.0 repository
      ansible.builtin.yum_repository:
        name: mongodb-org-7.0
        description: MongoDB 7.0 Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
        gpgcheck: yes
        gpgkey: https://pgp.mongodb.com/server-7.0.asc
        enabled: yes

    - name: Refresh package metadata
      ansible.builtin.dnf:
        update_cache: yes
...