- name: Configure existing MongoDB
  hosts: all
  become: true
  
  tasks:
    - name: Configure mongod.conf
      ansible.builtin.template:
        src: mongod.conf.j2
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: 0644
      notify: restart mongod

    - name: Secure MongoDB with admin user
      community.mongodb.mongodb_user:
        login_host: localhost
        login_port: 27017
        database: admin
        name: "{{ mongodb_admin_user }}"
        password: "{{ mongodb_admin_password }}"
        roles: root
        state: present

    - name: Ensure MongoDB is running
      ansible.builtin.service:
        name: mongod
        state: restarted
        enabled: yes

  handlers:
    - name: restart mongod
      ansible.builtin.service:
        name: mongod
        state: restarted