---
- name: Install and Configure MongoDB and Node.js on CentOS 9
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "3.86.98.40"
    mongodb_admin_user: "Eniola"
    mongodb_admin_password: "admin123!"
    node_project_path: "/var/www/devops-api"
    node_version: "18.x"
    node_user: "{{ ansible_user_id }}"  

  tasks:
  
    - name: Add NodeSource repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }} | bash -
      args:
        executable: /bin/bash
      register: nodesource_setup
      changed_when: "'Run as root' not in nodesource_setup.stdout"

    - name: Install Node.js and npm
      dnf:
        name: nodejs
        state: present
        disable_gpg_check: yes
      when: nodesource_setup is succeeded

    - name: Verify Node.js installation
      command: node --version
      register: node_version_check
      changed_when: false

    - name: Create Node.js project directory
      file:
        path: "{{ node_project_path }}"
        state: directory
        mode: 0755
        owner: "{{ node_user }}"
        group: "{{ node_user }}"

    - name: Deploy package.json
      copy:
        dest: "{{ node_project_path }}/package.json"
        content: |
          {
            "name": "devops-api",
            "version": "1.0.0",
            "main": "index.js",
            "scripts": {
              "start": "node index.js",
              "seed": "node init.js"
            },
            "dependencies": {
              "express": "^4.18.2",
              "mongoose": "^7.2.2"
            }
          }
        owner: "{{ node_user }}"
        group: "{{ node_user }}"
        mode: 0644

    - name: Install project dependencies
      npm:
        path: "{{ node_project_path }}"
        state: present
      when: node_version_check.rc == 0
      environment:
        NPM_CONFIG_PREFIX: "{{ node_project_path }}/.npm-global"
      vars:
        ansible_become_user: "{{ node_user }}"
...