---
- name: Install and Deploy MongoDB with Node.js App
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "172.31.86.23" 
    mongodb_admin_user: "Eniola"
    mongodb_admin_password: "admin123!"
    node_project_path: "/var/www/nodeapp"
    node_version: "18.x"
    node_user: "{{ ansible_user_id }}"
    app_repo: "https://github.com/Eniiwinner/mongodb-workk.git"
    app_branch: "main"
    mongodb_connection_timeout: 60

  tasks:

    - name: Add MongoDB GPG key
      rpm_key:
        state: present
        key: "https://www.mongodb.org/static/pgp/server-7.0.asc"

    - name: Add MongoDB repository
      yum_repository:
        name: mongodb-org-7.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-7.0.asc
        enabled: yes

    - name: Install MongoDB packages
      dnf:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-mongosh
          - mongodb-database-tools
        state: present

    - name: Create custom MongoDB config directory
      file:
        path: /etc/mongod.conf.d
        state: directory
        mode: 0755


    - name: Configure MongoDB to listen only on 172.31.86.23
      template:
        src: db.j2
        dest: /etc/db.conf
        owner: root
        group: root
        mode: 0644
      notify: restart mongod

    - name: Start and enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes
      async: 120
      poll: 0

    - name: Verify MongoDB is listening on correct IP
      shell: |
        ss -tulnp | grep '172.31.86.23:27017'
      register: mongo_listening
      changed_when: false
      failed_when: mongo_listening.rc != 0

    - name: Create admin user
      community.mongodb.mongodb_user:
        login_host: "172.31.86.23"
        login_port: 27017
        database: admin
        name: "{{ mongodb_admin_user }}"
        password: "{{ mongodb_admin_password }}"
        roles: "root"
        state: present
        update_password: always
      register: user_creation
      retries: 10
      delay: 15
      until: user_creation is succeeded


  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
...