---
- name: Install and Configure MongoDB on CentOS 9 and Create Admin User
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "172.31.86.23"
    mongodb_admin_user: "Eniola"
    mongodb_admin_password: "admin123!"
    mongodb_restart_timeout: 90 
    mongodb_connection_timeout: 90 
    mongodb_connection_retries: 5 

  tasks:

    - name: Temporarily disable authentication if enabled
      block:
        - name: Backup mongod.conf
          copy:
            src: /etc/mongod.conf
            dest: /etc/mongod.conf.bak
            remote_src: true

        - name: Disable authentication
          replace:
            path: /etc/mongod.conf
            regexp: '(?m)^(\s*)authorization:\s*enabled'
            replace: '\1# authorization: disabled_temp'
          notify: restart mongod

        - name: Verify MongoDB service is running
          systemd:
            name: mongod
            state: started
            enabled: yes
          register: mongo_service
          until: mongo_service is succeeded
          retries: 5
          delay: 10

        - name: Verify MongoDB is reachable (with retries)
          wait_for:
            host: "{{ mongodb_bind_ip }}"
            port: 27017
            timeout: "{{ mongodb_connection_timeout }}"
            delay: 10
          register: port_check
          until: port_check is succeeded
          retries: "{{ mongodb_connection_retries }}"
          ignore_errors: yes

        - name: Debug connection issues if any
          debug:
            msg: "MongoDB connection failed after multiple attempts. Check service status and logs."
          when: port_check is failed

      when: "'authorization: enabled' in auth_status.stdout"

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
      async: "{{ mongodb_restart_timeout }}"
      poll: 0