---
- name: Install and Configure MongoDB on CentOS 9
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "127.0.0.1"
    mongodb_admin_user: "Eniola"
    mongodb_admin_password: "admin123!"

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted

  tasks:
    - name: Add MongoDB GPG key
      rpm_key:
        state: present
        key: "https://www.mongodb.org/static/pgp/server-7.0.asc"

    - name: Add MongoDB repository
      yum_repository:
        name: mongodb-org-7.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-7.0.asc
        enabled: yes

    - name: Install MongoDB packages
      dnf:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-mongosh
          - mongodb-database-tools
        state: present

    - name: Create custom MongoDB config directory
      file:
        path: /etc/mongod.conf.d
        state: directory
        mode: 0755

    - name: Configure MongoDB
      template:
        src: mongod.j2
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: 0644
      notify: restart mongod

    - name: Ensure data directory permissions
      file:
        path: /var/lib/mongo
        owner: mongod
        group: mongod
        mode: '0755'
        recurse: yes

    - name: Start and enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes
      register: mongo_service
      until: mongo_service is succeeded
      retries: 5
      delay: 10

    - name: Install PyMongo dependency
      block:
        - name: Install pip (if not present)
          dnf:
            name: python3-pip
            state: present
          when: ansible_distribution == 'CentOS'

        - name: Install PyMongo using pip
          pip:
            name: pymongo
            executable: pip3
          register: pip_install
          until: pip_install is succeeded
          retries: 3
          delay: 5
      when: ansible_python.version.major == 3

    - name: Create admin user (initial attempt)
      community.mongodb.mongodb_user:
        login_host: "{{ mongodb_bind_ip }}"
        login_port: 27017
        database: admin
        name: "{{ mongodb_admin_user }}"
        password: "{{ mongodb_admin_password }}"
        roles: "root"
        state: present
      register: user_creation
      ignore_errors: yes

    - name: Temporarily disable authentication if first attempt failed
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  authorization:'
        line: '  authorization: disabled'
        state: present
      when: user_creation is failed
      notify: restart mongod

    - name: Create admin user (without auth)
      community.mongodb.mongodb_user:
        login_host: "{{ mongodb_bind_ip }}"
        login_port: 27017
        database: admin
        name: "{{ mongodb_admin_user }}"
        password: "{{ mongodb_admin_password }}"
        roles: "root"
        state: present
      when: user_creation is failed
      register: user_creation_noauth

    - name: Re-enable authentication
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  authorization:'
        line: '  authorization: enabled'
        state: present
      when: user_creation_noauth is succeeded
      notify: restart mongod

    - name: Verify admin user creation
      debug:
        msg: "Admin user creation status - First attempt: {{ user_creation is succeeded }}, Second attempt: {{ user_creation_noauth is succeeded if user_creation_noauth is defined else 'Not attempted' }}"

    - name: Update test page
      template:
        src: test.j2
        dest: /var/www/html
...