---
- name: Install and Configure MongoDB on CentOS 9 and Create Admin User
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "172.31.86.23"
    mongodb_admin_user: "Eniola"
    mongodb_admin_password: "admin123!"
    mongodb_restart_timeout: 60
    mongodb_connection_timeout: 60

  tasks:

    - name: Check MongoDB authentication status
      shell: |
        grep -A1 "security:" /etc/mongod.conf || echo "auth_not_found"
      args:
        executable: /bin/bash
      register: auth_status
      changed_when: false
      ignore_errors: true

    - name: Display authentication status
      debug:
        var: auth_status.stdout

    - name: Temporarily disable authentication if enabled
      block:
        - name: Backup mongod.conf
          copy:
            src: /etc/mongod.conf
            dest: /etc/mongod.conf.bak
            remote_src: true

        - name: Disable authentication
          replace:
            path: /etc/mongod.conf
            regexp: '(?m)^(\s*)authorization:\s*enabled'
            replace: '\1# authorization: disabled_temp'

        - name: Restart MongoDB
          service:
            name: mongod
            state: restarted
          async: "{{ mongodb_restart_timeout }}"
          poll: 0

        - name: Verify MongoDB is reachable
          wait_for:
            host: "{{ mongodb_bind_ip }}"
            port: 27017
            timeout: "{{ mongodb_connection_timeout }}"
            delay: 5

      when: "'authorization: enabled' in auth_status.stdout"

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
...