---
- name: Install and Configure MongoDB on CentOS 9
  hosts: n1
  become: true
  vars:
    mongodb_bind_ip: "127.0.0.1"  
    mongodb_admin_user: "admin"
    mongodb_admin_password: "admin123!"

  tasks:
  
    - name: Add MongoDB GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "https://www.mongodb.org/static/pgp/server-7.0.asc"

    - name: Add MongoDB repository
      ansible.builtin.yum_repository:
        name: mongodb-org-7.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-7.0.asc
        enabled: yes


    - name: Install MongoDB packages
      ansible.builtin.dnf:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-mongosh
          - mongodb-database-tools 
        state: present


    - name: Create custom MongoDB config directory
      ansible.builtin.file:
        path: /etc/mongod.conf.d
        state: directory
        mode: 0755

    - name: Configure MongoDB
      ansible.builtin.template:
        src: db.j2
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: 0644
      notify: restart mongod

    - name: Start and enable MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Install PyMongo via dnf (preferred method for CentOS)
      ansible.builtin.dnf:
        name: python3-pymongo
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install PyMongo via pip (fallback)
      ansible.builtin.pip:
        name: pymongo
        executable: pip3
      when: ansible_python.version.major == 3 and not ansible_distribution == 'CentOS'
      ignore_errors: yes

    - name: Create admin user
      community.mongodb.mongodb_user:
        login_host: "127.0.0.1"
        login_port: 27017
        database: admin
        name: "{{ mongodb_admin_user }}"
        password: "{{ mongodb_admin_password }}"
        roles: "root"
        state: present
      register: user_creation
      until: user_creation is succeeded
      retries: 3
      delay: 5

  handlers:
    - name: restart mongod
      ansible.builtin.service:
        name: mongod
        state: restarted
...