- name: Install and Deploy Node.js App on CentOS
  hosts: n1
  become: yes
  tasks:

    - name: Add Node.js repo
      shell: curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install Git
      yum:
       name: git
       state: present

    - name: Clone Node.js app repo
      git:
        repo: https://github.com/Eniiwinner/mongodb-workk.git
        dest: /var/www/nodeapp
        version: main
        force: yes
        update: yes

    - name: Install Node.js dependencies
      npm:
        path: /var/www/nodeapp
        production: yes

    - name: Create .env file
      copy:
        dest: /var/www/nodeapp/.env
        content: |
          PORT=3000
          MONGO_URI=mongodb://localhost:27017/mydb

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Start Node.js app with PM2
      shell: |
        pm2 start app.js --name myapp
        pm2 save
        pm2 startup
      args:
        chdir: /var/www/nodeapp
