---
- name: Variables Custom
  hosts: g1
  become: yes
  vars:
    mongodb_bind_ip: "3.86.98.40"  
    mongodb_admin_user: "Eniola"
    mongodb_admin_password: "admin123!"
    myusername: "Eniola"

  tasks:
    - name: Update Test page
      template:
        src: html.j2
        dest: /var/www/html/test.html
...